# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MCBEDOC
description: MCBEDOC - An Ultimate Collection of MCBE Tools & Unlockers
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mcbedoc.openm.tech" # the base hostname & protocol for your site, e.g. http://example.com
repository: OpenMicrosoft-Project/mcbedoc.github.io # for github-metadata

permalink: pretty

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
 # specific to the theme website:
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - LICENSE.txt
   - package.json
   - package-lock.json
   - Rakefile
   - README.md
   - CODE_OF_CONDUCT.md
   - docker-compose.yml
   - Dockerfile
 # theme test code
   - fixtures/

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/favicon.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# For copy button on code
enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/Windows/code
  # To load mermaid from a local library, also use the `path` key to specify the location of the library; e.g.
  # for (v10+):
  # path: "/assets/js/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="53px" height="52px" viewBox="0 0 53 52" version="1.1">
<g id="surface1">
<path style=" stroke:none;fill-rule:evenodd;fill:rgb(100%,100%,100%);fill-opacity:1;" d="M 26.421875 0 C 11.8125 0 0 11.917969 0 26.660156 C 0 38.445312 7.566406 48.417969 18.066406 51.949219 C 19.378906 52.214844 19.859375 51.375 19.859375 50.671875 C 19.859375 50.050781 19.816406 47.933594 19.816406 45.726562 C 12.464844 47.316406 10.9375 42.546875 10.9375 42.546875 C 9.753906 39.457031 8.003906 38.664062 8.003906 38.664062 C 5.597656 37.03125 8.179688 37.03125 8.179688 37.03125 C 10.847656 37.207031 12.25 39.769531 12.25 39.769531 C 14.609375 43.828125 18.414062 42.679688 19.945312 41.976562 C 20.164062 40.253906 20.867188 39.0625 21.609375 38.398438 C 15.746094 37.78125 9.578125 35.488281 9.578125 25.246094 C 9.578125 22.332031 10.628906 19.949219 12.292969 18.097656 C 12.03125 17.433594 11.109375 14.699219 12.554688 11.035156 C 12.554688 11.035156 14.785156 10.328125 19.816406 13.769531 C 21.96875 13.1875 24.191406 12.890625 26.421875 12.886719 C 28.652344 12.886719 30.925781 13.195312 33.027344 13.769531 C 38.058594 10.328125 40.289062 11.035156 40.289062 11.035156 C 41.730469 14.699219 40.8125 17.433594 40.550781 18.097656 C 42.257812 19.949219 43.261719 22.332031 43.261719 25.246094 C 43.261719 35.488281 37.09375 37.738281 31.1875 38.398438 C 32.152344 39.238281 32.980469 40.828125 32.980469 43.34375 C 32.980469 46.917969 32.9375 49.789062 32.9375 50.667969 C 32.9375 51.375 33.421875 52.214844 34.730469 51.949219 C 45.230469 48.417969 52.796875 38.445312 52.796875 26.660156 C 52.839844 11.917969 40.988281 0 26.421875 0 Z M 26.421875 0 "/>
</g>
</svg>
":
    - "https://github.com/OpenMicrosoft-Project/mcbedoc.github.io"
  "OpenMicrosoft Project website":
    - "https://openm.tech/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
# nav_external_links:
#  - title: MCBEDOC on GitHub
#    url: https://github.com/OpenMicrosoft-Project/mcbedoc.github.io

liquid:
   error_mode: strict
   strict_filters: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/OpenMicrosoft-Project/mcbedoc.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-4VXN2ZNNNS
ga_tracking_anonymize_ip: false # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
